USE [master]
GO
/****** Object:  Database [zadanie]    Script Date: 8. 7. 2021 13:40:41 ******/
CREATE DATABASE [zadanie]
GO
ALTER DATABASE [zadanie] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [zadanie].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [zadanie] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [zadanie] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [zadanie] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [zadanie] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [zadanie] SET ARITHABORT OFF 
GO
ALTER DATABASE [zadanie] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [zadanie] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [zadanie] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [zadanie] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [zadanie] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [zadanie] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [zadanie] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [zadanie] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [zadanie] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [zadanie] SET  DISABLE_BROKER 
GO
ALTER DATABASE [zadanie] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [zadanie] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [zadanie] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [zadanie] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [zadanie] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [zadanie] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [zadanie] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [zadanie] SET RECOVERY FULL 
GO
ALTER DATABASE [zadanie] SET  MULTI_USER 
GO
ALTER DATABASE [zadanie] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [zadanie] SET DB_CHAINING OFF 
GO
ALTER DATABASE [zadanie] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [zadanie] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [zadanie] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [zadanie] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'zadanie', N'ON'
GO
ALTER DATABASE [zadanie] SET QUERY_STORE = OFF
GO
USE [zadanie]
GO
/****** Object:  Table [dbo].[person_role]    Script Date: 8. 7. 2021 13:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[person_role](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PersonId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
	[ValidFrom] [date] NOT NULL,
	[ValidTo] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Persons]    Script Date: 8. 7. 2021 13:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Persons](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](255) NOT NULL,
	[LastName] [varchar](255) NOT NULL,
	[Address] [varchar](255) NULL,
	[DateOfBirth] [date] NOT NULL,
	[ValidFrom] [date] NOT NULL,
	[Salary] [float] NOT NULL,
	[Archived] [bit] NOT NULL,
	[ValidTo] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 8. 7. 2021 13:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RoleName] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Persons] ADD  DEFAULT ((0)) FOR [Archived]
GO
ALTER TABLE [dbo].[person_role]  WITH CHECK ADD FOREIGN KEY([PersonId])
REFERENCES [dbo].[Persons] ([Id])
GO
ALTER TABLE [dbo].[person_role]  WITH CHECK ADD FOREIGN KEY([RoleId])
REFERENCES [dbo].[Roles] ([Id])
GO
USE [master]
GO
ALTER DATABASE [zadanie] SET  READ_WRITE 
GO
USE [zadanie]
GO
INSERT INTO [dbo].[Roles]([RoleName]) VALUES ('Tester')
INSERT INTO [dbo].[Roles]([RoleName]) VALUES ('Programátor')
INSERT INTO [dbo].[Roles]([RoleName]) VALUES ('Support')
INSERT INTO [dbo].[Roles]([RoleName]) VALUES ('Analytik')
INSERT INTO [dbo].[Roles]([RoleName]) VALUES ('Obchodník')
INSERT INTO [dbo].[Roles]([RoleName]) VALUES ('Iné')

